package openapithrift

import (
	"fmt"
	"regexp"
	"strings"
)

type ProjectionOptions struct {
	Namespace        string            `json:"namespace,omitempty"`
	ServiceName      string            `json:"serviceName,omitempty"`
	RouteMethodNames map[string]string `json:"routeMethodNames,omitempty"`
}
type ProjectionResult struct {
	Document ThriftDocument `json:"document"`
	Thrift   string         `json:"thrift"`
}
type ThriftDocument struct {
	Namespace   string         `json:"namespace"`
	ServiceName string         `json:"serviceName"`
	Definitions []ThriftStruct `json:"definitions"`
	Methods     []ThriftMethod `json:"methods"`
}
type ThriftStruct struct {
	Name    string        `json:"name"`
	Comment []string      `json:"comment,omitempty"`
	Fields  []ThriftField `json:"fields"`
}
type ThriftField struct {
	ID           int      `json:"id"`
	Requiredness string   `json:"requiredness"`
	Type         string   `json:"type"`
	Name         string   `json:"name"`
	Annotations  []string `json:"annotations"`
	Comment      []string `json:"comment,omitempty"`
}
type ThriftMethod struct {
	Name         string   `json:"name"`
	RequestType  string   `json:"requestType"`
	ResponseType string   `json:"responseType"`
	HTTPMethod   string   `json:"httpMethod"`
	Path         string   `json:"path"`
	Comment      []string `json:"comment,omitempty"`
}
type ThriftSourceFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

type ProjectionError struct {
	Message string `json:"message"`
	Pointer string `json:"pointer,omitempty"`
}

func (e *ProjectionError) Error() string {
	if e.Pointer != "" {
		return e.Message + " (" + e.Pointer + ")"
	}
	return e.Message
}
func projectionError(message, pointer string) error { return &ProjectionError{message, pointer} }

var routePattern = regexp.MustCompile(`[A-Za-z_][A-Za-z0-9_<>.]*\s+([A-Za-z_][A-Za-z0-9_]*)\s*\([^)]*\)\s*\(\s*api\.(get|post|put|delete|patch|head|options|any)\s*=\s*"([^"]+)"`)
var pathParameter = regexp.MustCompile(`\{([^}]+)\}`)
var camelBoundary = regexp.MustCompile(`([a-z0-9])([A-Z])`)
var nameSeparator = regexp.MustCompile(`[^A-Za-z0-9]+`)
var versionSegment = regexp.MustCompile(`^v\d+$`)

func BuildRouteKey(method, path string) string {
	return strings.ToUpper(method) + " " + NormalizeRoutePath(path)
}
func NormalizeRoutePath(path string) string { return pathParameter.ReplaceAllString(path, ":$1") }
func ExtractRouteMethodNames(files []ThriftSourceFile) map[string]string {
	result := map[string]string{}
	for _, file := range files {
		for _, match := range routePattern.FindAllStringSubmatch(file.Content, -1) {
			result[BuildRouteKey(match[2], match[3])] = match[1]
		}
	}
	return result
}

func RenderThrift(document ThriftDocument) string {
	lines := []string{"// Generated by @sttot/openapi-thrift", "// Unsupported OpenAPI features fail fast by design.", "", "namespace go " + document.Namespace}
	comment := func(values []string, indent string) {
		for _, line := range values {
			lines = append(lines, indent+"// "+line)
		}
	}
	for _, definition := range document.Definitions {
		lines = append(lines, "")
		comment(definition.Comment, "")
		lines = append(lines, "struct "+definition.Name+" {")
		for _, field := range definition.Fields {
			comment(field.Comment, "  ")
			annotations := ""
			if len(field.Annotations) > 0 {
				annotations = " (" + strings.Join(field.Annotations, ", ") + ")"
			}
			lines = append(lines, fmt.Sprintf("  %d: %s %s %s%s", field.ID, field.Requiredness, field.Type, field.Name, annotations))
		}
		lines = append(lines, "}")
	}
	lines = append(lines, "", "service "+document.ServiceName+" {")
	for _, method := range document.Methods {
		comment(method.Comment, "  ")
		lines = append(lines, fmt.Sprintf("  %s %s(1: %s req) (api.%s=\"%s\")", method.ResponseType, method.Name, method.RequestType, method.HTTPMethod, method.Path))
	}
	return strings.Join(append(lines, "}", ""), "\n")
}

func pascal(value string) string {
	parts := nameSeparator.Split(camelBoundary.ReplaceAllString(value, "$1 $2"), -1)
	var b strings.Builder
	for _, part := range parts {
		if part != "" {
			b.WriteString(strings.ToUpper(part[:1]))
			b.WriteString(part[1:])
		}
	}
	return b.String()
}
func snake(value string) string {
	parts := nameSeparator.Split(camelBoundary.ReplaceAllString(value, "${1}_${2}"), -1)
	filtered := []string{}
	for _, part := range parts {
		if part != "" {
			filtered = append(filtered, part)
		}
	}
	return strings.ToLower(strings.Join(filtered, "_"))
}
func fallbackMethod(method, path string) string {
	parts := []string{}
	for _, part := range strings.Split(NormalizeRoutePath(path), "/") {
		if part == "" || part == "api" || versionSegment.MatchString(part) {
			continue
		}
		if strings.HasPrefix(part, ":") {
			part = "by-" + part[1:]
		}
		parts = append(parts, pascal(part))
	}
	suffix := strings.Join(parts, "")
	if suffix == "" {
		suffix = "Operation"
	}
	return pascal(method) + suffix
}
func comments(values ...string) []string {
	var result []string
	for _, value := range values {
		for _, line := range strings.Split(value, "\n") {
			if line = strings.TrimSpace(line); line != "" {
				result = append(result, line)
			}
		}
	}
	return result
}
