// Generated by @sttot/openapi-thrift
// Unsupported OpenAPI features fail fast by design.

namespace go dramawork.boundarylab.supported

// Mutation target: multiple success responses
struct Multi2xxCandidateRequest {
}

struct OkResponse {
  1: optional bool ok (go.tag='validate:"required"')
  2: optional string request_id (go.tag='validate:"required,uuid"')
}

// Mutation target: nullable anyOf
struct NullableAnyOfCandidateRequest {
  1: optional string nickname (api.body="nickname", go.tag='validate:"required,min=2,max=16"')
}

struct MutationNullableResponse {
  1: optional string nickname (go.tag='validate:"required,min=2,max=16"')
}

// Mutation target: non-default query array serialization
struct QueryArrayCandidateRequest {
  1: optional list<string> tags (api.query="tags")
}

// Mutation target: object query or deepObject
struct QueryObjectCandidateRequest {
  1: optional string filter_keyword (api.query="filter_keyword", go.tag='validate:"min=1,max=32"')
  2: optional i32 limit (api.query="limit", go.tag='default:"5" validate:"gte=1,lte=10"')
}

// Mutation target: parameter $ref
struct RefParameterCandidateRequest {
  1: required string item_id (api.path="item_id", go.tag='validate:"uuid"')
  2: optional string locale (api.query="locale", go.tag='default:"zh-CN" validate:"oneof=zh-CN en-US"')
}

// Update preferences via form-urlencoded
struct UpdatePreferencesRequest {
  1: optional string theme (api.form="theme", go.tag='default:"system" validate:"required,oneof=light dark system"')
  2: optional string timezone (api.form="timezone", go.tag='validate:"required,min=3,max=64"')
  3: optional bool daily_digest (api.form="daily_digest", go.tag='default:"false"')
  4: optional i32 weekly_limit (api.form="weekly_limit", go.tag='default:"20" validate:"gte=1,lte=50"')
}

// Top-level scalar requestBody fallback
struct ValidateRawJsonRequest {
  1: optional string body (api.raw_body="", go.tag='validate:"required,json"')
}

// Search profiles with repeated-key query array
struct SearchProfilesRequest {
  1: optional string debug_token (api.cookie="debug_token", go.tag='validate:"min=8,max=64"')
  2: optional string keyword (api.query="keyword", go.tag='validate:"required,min=1,max=32"')
  3: optional list<string> tags (api.query="tags", go.tag='validate:"min=1,max=5"')
  4: optional i32 page_size (api.query="page_size", go.tag='default:"20" validate:"gte=1,lte=50"')
  5: optional string x_request_id (api.header="X-Request-Id", go.tag='validate:"required,uuid"')
}

struct ProfileSummary {
  1: optional string profile_id (go.tag='validate:"required,uuid"')
  2: optional string display_name (go.tag='validate:"required"')
  3: optional string role (go.tag='validate:"required,oneof=user admin reviewer"')
}

struct SearchProfilesResponse {
  1: optional i32 total (go.tag='validate:"required,gte=0"')
  2: optional list<ProfileSummary> items (go.tag='validate:"required"')
}

// Prepare upload metadata via multipart form
struct PrepareUploadMetaRequest {
  1: optional string bucket (api.form="bucket", go.tag='validate:"required,min=3,max=32"')
  2: optional string object_key (api.form="object_key", go.tag='validate:"required,min=1,max=128"')
  3: optional string checksum (api.form="checksum", go.tag='validate:"min=8,max=128"')
  4: optional string content_type (api.form="content_type", go.tag='validate:"required,oneof=image/png image/jpeg application/pdf"')
  5: optional i64 size_bytes (api.form="size_bytes", go.tag='validate:"required,gte=1,lte=10485760"')
}

struct UploadMetaResponse {
  1: optional string upload_token (go.tag='validate:"required,base64"')
  2: optional string expires_at (go.tag='validate:"required,datetime=2006-01-02T15:04:05Z07:00"')
}

service BoundaryLabSupportedService {
  // Mutation target: multiple success responses
  OkResponse Multi2xxCandidate(1: Multi2xxCandidateRequest req) (api.get="/v1/lab/mutation/multi-2xx")
  // Mutation target: nullable anyOf
  MutationNullableResponse NullableAnyOfCandidate(1: NullableAnyOfCandidateRequest req) (api.post="/v1/lab/mutation/nullable-anyof")
  // Mutation target: non-default query array serialization
  OkResponse QueryArrayCandidate(1: QueryArrayCandidateRequest req) (api.get="/v1/lab/mutation/query-array")
  // Mutation target: object query or deepObject
  OkResponse QueryObjectCandidate(1: QueryObjectCandidateRequest req) (api.get="/v1/lab/mutation/query-object")
  // Mutation target: parameter $ref
  OkResponse RefParameterCandidate(1: RefParameterCandidateRequest req) (api.get="/v1/lab/mutation/ref-parameter/:item_id")
  // Update preferences via form-urlencoded
  OkResponse UpdatePreferences(1: UpdatePreferencesRequest req) (api.post="/v1/lab/preferences")
  // Top-level scalar requestBody fallback
  OkResponse ValidateRawJson(1: ValidateRawJsonRequest req) (api.post="/v1/lab/raw-json")
  // Search profiles with repeated-key query array
  SearchProfilesResponse SearchProfiles(1: SearchProfilesRequest req) (api.get="/v1/lab/search")
  // Prepare upload metadata via multipart form
  UploadMetaResponse PrepareUploadMeta(1: PrepareUploadMetaRequest req) (api.post="/v1/lab/uploads/meta")
}
